Test: 프론트엔드 nginx 연결 Test
15 4.490 src/mocks/handlers.ts(13,67): error TS6133: 'req' is declared but its value is never read.
해당 파일 수정